global:
  scrape_interval: 10s
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - prometheus:9090
  - job_name: node
    static_configs:
      - targets:
          - server:3000
          - customers:3000
          - notification:3000
          - orchestrator:3000
