name: Server CI
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  build-server:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21.x'
      - name: Install dependencies
        run: cd ./server && npm ci
      - name: Build
        run: cd ./server && npm run build

  lint-server:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21.x'
      - name: Install dependencies
        run: cd ./server && npm ci
      - name: Lint Server
        run: cd ./server && npm run lint

  test-server:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21.x'
      - name: Install dependencies
        run: cd ./server && npm ci
      - name: Run server unit tests
        run: cd ./server && npm run test

  build-notification:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21.x'
      - name: Install dependencies
        run: cd ./notification && npm ci
      - name: Build
        run: cd ./notification && npm run build

  lint-notification:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21.x'
      - name: Install dependencies
        run: cd ./notification && npm ci
      - name: Lint
        run: cd ./notification && npm run lint

  test-notification:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21.x'
      - name: Install dependencies
        run: cd ./notification && npm ci
      - name: Run server unit tests
        run: cd ./notification && npm run test
